### ISSUE TITLE
Need to be improved

### ISSUE THREAD

**Issue by hmsjy2017** [raspbian-addons/raspbian-addons.github.io#12]
The installation page looks terrible, it needs to be improved. In addition, the logo on the homepage cannot be displayed well when the screen is small.
<img src="https://user-images.githubusercontent.com/42692274/143688747-4dcbd942-1a09-4aed-a9d0-e71446515df8.jpeg" height="840" width="370" />

**Comment by ryanfortner** [comment]
@hmsjy2017 I've touched up the installation page a little bit. As for the home page, I'll work on it.

**Comment by hmsjy2017** [comment]
@ryanfortner I found that the page cannot be dragged up and down when the iPad is in landscape orientation. This should be fixed.
![70B207D8-BC10-4F2A-932C-12E66BBCBF32](https://user-images.githubusercontent.com/42692274/143888228-62a14fd2-d626-4ef8-a41c-8d29570edd39.png)

**Comment by ryanfortner** [comment]
Well, I think we may need a better looking website, so I am customizing a template here: https://ryanfortner.github.io/siteexperiment/

**Comment by hmsjy2017** [comment]
@ryanfortner Looks great! 
But I think it may not be necessary to use another repository to store the installation instructions. It can be incorporated into the docs.

**Comment by ryanfortner** [comment]
> @ryanfortner Looks great! But I think it may not be necessary to use another repository to store the installation instructions. It can be incorporated into the docs.

I added an install page: https://docs.raspbian-addons.org/install/

Does everything look good? If so, I'll go ahead and merge with this repo.
