### ISSUE TITLE
ERR_TOO_MANY_REDIRECTS

### ISSUE THREAD

**Issue by hmsjy2017** [raspbian-addons/raspbian-addons.github.io#5]
When I visit raspbian-addons.org, the browser prompts ERR_TOO_MANY_REDIRECTS. This problem cannot be solved even after refreshing multiple times. When I visit raspbian-addons.org, the browser prompts ERR_TOO_MANY_REDIRECTS. This problem cannot be solved even after refreshing multiple times. Setting Cloudflare's SSL/TLS encryption mode to "Full" may solve this problem.

**Comment by ryanfortner** [comment]
> When I visit raspbian-addons.org, the browser prompts ERR_TOO_MANY_REDIRECTS. This problem cannot be solved even after refreshing multiple times. When I visit raspbian-addons.org, the browser prompts ERR_TOO_MANY_REDIRECTS. This problem cannot be solved even after refreshing multiple times. Setting Cloudflare's SSL/TLS encryption mode to "Full" may solve this problem.

Try again, does the message still appear?

**Comment by hmsjy2017** [comment]
The problem disappeared. However, the loading speed seems to be slower than when the CDN is not used.
